### ISSUE TITLE
编码器内部报java.lang.IllegalStateException 

### ISSUE THREAD

**Issue by hawskpy** [WangShuo1143368701/VideoView#1]
05-21 17:34:11.586 6586-6586/com.ws.mediacodecdemo W/System.err: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2505)
        at com.ws.mediacodecdemo.AvcEncoder.offerEncoder(AvcEncoder.java:67)
        at com.ws.mediacodecdemo.EncodeActivity.onPreviewFrame(EncodeActivity.java:157)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1204)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6605)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)

你好，最近一直在做Android 视频RTP相关的功能，摄像头视频数据编码总是越到上面错误，你那边有遇到吗？  
复现机型：荣耀Waterplay，Google Pixel XL

**Comment by WangShuo1143368701** [comment]
建议你用软编码，华为部分手机硬编问题很大。
